# Generated by Django 6.0 on 2026-02-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the author', max_length=100, verbose_name='Author Name')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the book', max_length=200, verbose_name='Book Title')),
                ('publication_year', models.IntegerField(help_text='Enter the year the book was published', verbose_name='Publication Year')),
                ('author', models.ForeignKey(help_text='Select the author of this book', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author', verbose_name='Book Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('title', 'author'), name='unique_book_per_author')],
            },
        ),
    ]
